### ISSUE TITLE
Double tracks / albums in library view

### ISSUE THREAD

**Issue by PiotrC1** [CDrummond/cantata#1697] opened 2021-03-19 13:07 UTC
I have my collection in a form of folders each containig whole CD as one `.flac` and `.cue` file pointing to this flac. If `.flac` file contains any tags, especially if `Album` tag is empty or contains any other name (different from `TITLE` contained in .cue file) then album is shown double in `Library`. After changing `Album` tag to the same value like `TITLE` contained in `.cue` file everything goes normal again.

Solution might be additional option to ignore tags of `.flac` (or any other music file) when `.cue` file exists?

**Comment by CDrummond** [comment] 2021-03-19 13:13
Please look for duplicates **before* opening reports - Duplicate of #1650

**Closed** 2021-03-19 13:13 UTC
Labels: duplicate
