### ISSUE TITLE
Cue files are not being processed

### ISSUE THREAD

**Issue by Goresome** [CDrummond/cantata#801] opened 2016-02-04 19:12 UTC
In 2.0 .cue files are no longer being parsed for me, despite having them enabled ('Parse in Library view, show in Folders view'). So albums that relied on cue files to populate them with proper tracks have only 'Unknown' now.

However, play queue composed from tracks from cue files, that is leftover from 1.5.5, is still playable. 'Locate in library' performed on such tracks does nothing.

**Comment by CDrummond** [comment] 2016-02-04 23:01
Was caused by an 'optimisation' elsewhere. Should be fixed - in 2.0 branch and master. Can you update and confirm?

**Comment by Goresome** [comment] 2016-02-05 05:01
Tried 55fb716 and it works as far as I can see.

**Comment by CDrummond** [comment] 2016-02-05 08:07
Thanks for the confirmation.

**Closed by CDrummond** 2016-02-05 08:07 UTC
