### ISSUE TITLE
Duplicated empty album are present on Artist

### ISSUE THREAD

**Issue by DarkSwan86** [CDrummond/cantata#1686] opened 2021-02-18 17:46 UTC
Hi!

I have a problem with Cantata 2.4.2 on Manjaro KDE, there are some duplicates album inside my library that are "empty". 

![errorcantata](https://user-images.githubusercontent.com/24975273/108397810-a8b2be00-7218-11eb-91ef-d3a5b05fa30e.png)

As you see on the image there is a duplicate album with an Unknown duration. 

Cue files setting is "Do not List" so i don't think it's here the problem.

Cantata is using the default Music folder, inside there are only FLAC files, divided int Artist/Album folders.

 Is is a regression? My database is corrupted?

Server version: 0.22.4, Cantata 2.4.2

If you need more information, just ask! Thanks for this fantastic software!

**Comment by CDrummond** [comment] 2021-02-18 23:03
No idea, I get no such duplicates so this _must_ be an issue with your setup. Do all these duplicate albums have CUE sheets? If so, does it happen to all the have CUE sheets, or only some?

**Comment by DarkSwan86** [comment] 2021-02-22 15:35
It's something about CUEs. If i change the extension from .cue to .cuexx for example and refresh the database is all fixed for that album. 

I've also triple check that the option Cue Files is "Do not List".

I hope this information can be useful

**Comment by CDrummond** [comment] 2021-02-22 15:42
Then this listing is coming from MPD. If Cantata is not listing CUE files it will not process them. I guess you have CUE files with multiple source files, and MPD sees both. Sorry, but not much I can do there. Have you configured MPD to use its CUE directory plugin? (Not sure what this is called exactly, but its a new MPD feature where it reads CUE files and passes contents on to client).

Anyhow, duplication **must** be comming from MPD.

**Comment by DarkSwan86** [comment] 2021-02-22 18:51
Where i can find the configuration file of MPD to check this thing about CUE? Thanks!

**Comment by CDrummond** [comment] 2021-02-22 21:27
Ah, so this bug is a duplicate of https://github.com/CDrummond/cantata/issues/1650

**Closed by CDrummond** 2021-02-22 21:27 UTC
Labels: duplicate
