### ISSUE TITLE
Function "Locate in Library / Album" does not work

### ISSUE THREAD

**Issue by chrober** [CDrummond/cantata#1324] opened 2018-07-07 10:55 UTC
When right-clicking on a song in the play queue one sees the item "Locate in Library" in the context menu. Its flyout menu offers the three options "Artist", "Album", and "Song", where "Album" option seems to be broken. When choosing "Album" nothing happens (I would expect to get the corresponding album selected in the library pane.) For "Artist" and "Song" everything works as expected.

I am observing this behaviour with v2.3.1 running on Windows 10 as well as with a self-built binary on Linux based on master commit f6669f6.

**Comment by CDrummond** [comment] 2018-07-07 13:35
It's working for me. Is it one specific song/album?

**Comment by chrober** [comment] 2018-07-07 13:50
It is not just one specific album. Actually, before your feedback I would have claimed it does not work at all (since I've never seen it working until now).

Now that you asked I tried certain albums, where I know there are some differences... And I found two albums where "Locate in Library / Album" did work! The files from these albums are not tagged with MusicBrainz information. Could this be related?

**Comment by CDrummond** [comment] 2018-07-07 20:50
Ah! I'm 99.9999% sure that will be the cause! I don't use music brainz ids - hence why it is always working for me. I'll try and fix for 2.3.2. Thanks for the info.

**Comment by CDrummond** [comment] 2018-07-09 15:38
Should be fixed in git/master for 2.3.2 - can you checkout and confirm?

**Comment by chrober** [comment] 2018-07-10 21:30
Hi Craig,
I just pulled the latest code...
```
From http://github.com/CDrummond/cantata
   f6669f60..c480caf7  master     -> origin/master
Updating f6669f60..c480caf7
```
...and can confirm "Locate in Library / Album" is working now for albums where it not work before! (of course, I did not test all of my albums but only a handfull where I am sure they are tagged with MusicBrainz information)

Well done, thank you very much!

Cheers, Christoph

**Comment by CDrummond** [comment] 2018-07-11 06:37
Thanks for the confirmation! Will try to release 2,3,2 soon - when I have the spare time!

**Closed by CDrummond** 2018-07-11 06:37 UTC
Labels: bug
