### ISSUE TITLE
Cannot playback OGG MPD HTTP stream

### ISSUE THREAD

**Issue by pztrn** [CDrummond/cantata#1122] opened 2017-11-12 13:00 UTC
My MPD configured as:

```
audio_output {
	type		"httpd"
	name		"My HTTP Stream"
	encoder		"vorbis"		# optional, vorbis or lame
	port		"9999"
	bind_to_address "0.0.0.0"               # optional, IPv4 or IPv6
	quality		"5.0"			# do not define if bitrate is defined
#	bitrate		"128"			# do not define if quality is defined
#	format		"44100:16:1"
#	max_clients     "0"                     # optional 0=no limit
	always_on	"yes"
	tags		"yes"
}
```

Stream URL configured in connection options, but nothing is playing from speakers. When I'm going to stream URL using browser - all ok here. MP3 stream playing ok.

**Comment by CDrummond** [comment] 2017-11-12 14:23
Cantata (for macOS/Windows) uses QtMultimedia for stream playback. If this is not working, then I guess the issue is there.

Either way, not something I have time to look into. I use neither macOS, or MPD HTTP stream playback. I've often thought of disabling this feature, as I do not like the inherent delay.

**Comment by pztrn** [comment] 2017-11-18 13:22
I would ask not to remove this feature. Actually, Cantana is the very only usable cross-platform MPD client which able to playback stream from MPD.

As "workaround" I would suggest to mention in README that on macOS only mp3 streams can be played. I'm about to test Linux now, right when Debian package will be built.

**Comment by CDrummond** [comment] 2017-11-18 13:34
It's more than likely due to a missing library to decode the ogg stream. But as I don't use macOS, I have no idea what this is.

**Comment by theirix** [comment] 2018-09-15 18:57
Seems the problem is not about ogg or mp3. It is caused by the strange undocumented behaviour of QMediaPlayer that could be fixed with the PR.

**Comment by CDrummond** [comment] 2018-12-30 10:56
Sorry, but I have decided to no longer produce mac and windows builds - as I use neither OSs. Therefore, features/issues that specific to these are not on my list of priorities. However, please feel free to implement and submit a pull request.

**Closed by CDrummond** 2018-12-30 10:56 UTC
Labels: Windows, help wanted, macOS, wontfix
