### ISSUE TITLE
Cantata does not show when 'Show Window' is click on the indicator.

### ISSUE THREAD

**Issue by nemonein** [CDrummond/cantata#822] opened 2016-03-15 09:15 UTC
Hi. Thanks for your great effort. I really like Cantata.

I've build a Deb pacakge from 0278b57 on Ubuntu 16.04(64bit), and there were no problem at all.
I used these dependencies.
`Build-Depends: debhelper (>= 8.0.0), cmake, libx11-dev, libqt4-dev, qt4-dev-tools, qt5-default, qttools5-dev, libqt5svg5-dev, qttools5-dev-tools, libtag1-dev, libcdparanoia-dev, libcddb2-dev, libmusicbrainz5-dev, libmtp-dev, libmpg123-dev, libmp3lame-dev, libphonon-dev, libtag-extras-dev, libspeexdsp-dev, libudev-dev, libavcodec-dev, libavformat-dev, libqjson-dev, libebur128-dev, libvlc-dev, libvlccore-dev`

Cantata works fine, but there are some problems.
I set Cantata as 'Show Icon in notification area' and 'Minimize to notification area when closed'.
After I close(actually minimized) Cantata, I want to show up the Cantata window by right clicking the icon in the indicator, and select 'Show Window'.
Sometimes it shows, but most of the times, nothing happens.

And another one, which has been existed from Ubuntu 15.10, and Cantata 2.0.0.
Even if Cantata can wake up and show up, the menus are missing on the menu bar(Top screen).

Cantata without Menu.
![cantata_1](https://cloud.githubusercontent.com/assets/5688288/13772704/dd2a9080-ead8-11e5-85bf-d5f933193753.png)

Cantata with Menu.
![cantata_2](https://cloud.githubusercontent.com/assets/5688288/13772779/4545b92e-ead9-11e5-80dd-5433bac888b7.png)

I hope you could find what causes these.

Regards,
J.

**Comment by CDrummond** [comment] 2016-03-16 08:15
The 1st issue is an issue with compiz. Try install wmctrl - the Qt5 builds should call this to raise the window.

**Comment by nemonein** [comment] 2016-03-16 12:58
I don't know why and how, wmctrl was already installed.
`plainbox-provider-checkbox` depends on it, and wmctrl was installed during some other program was being installed.

Anyway, whether wmctrl is installed or not, `not-show-up` occurs from time to time.

And there's one more thing I'd like to mention.
I don't know it's related, when Cantata shows up, it does not remember it's prior window position.

I close the window here.
![cantata-1](https://cloud.githubusercontent.com/assets/5688288/13812888/ddbb2624-ebc1-11e5-9287-24ae7ae5715f.png)

Cantata shows up there.
![cantata-2](https://cloud.githubusercontent.com/assets/5688288/13812898/ea32d596-ebc1-11e5-8c2b-efacf9b7b756.png)

**Comment by CDrummond** [comment] 2016-03-16 18:12
So, you are now sating 'Show window' sometimes works? Just tried on 15.10 and its *always* working for me. Cantata does try to restore the window position - and its sort of working for me. The issue is that it seems to move to the left about 16 pixels each time its shown.

But I can confirm the menubar issue.

**Comment by CDrummond** [comment] 2016-03-16 22:04
I'm pretty sure this menubar issue again is a Unity issue. Try VLC, it has the same problem.

**Comment by nemonein** [comment] 2016-03-17 02:25
Maybe because Ubuntu 16.04 is in beta status, something is not working as intended.

I'm running two Ubuntu 16.04, one is my desktop(Intel based pc, and also Intel Graphic driver), and Virtual box.

On 'Show Windows' Issue,
In virtual box, 'Show Window' almost always works, while in my desktop(with Dual monitor), not always works.

On Previous Window Position Issue,
Both in VB and desktop, Cantata does not remember it's position. It tends to show up at the corners. Top-Left, Top-Right, Bottom-Left, or Bottom-Right. I can't say it randomly chooses it's position, but it opens the window (not from showing up from indicator, but from initial start from unity launcher) at top-left position on VB, and at bottom-right posion on my desktop.

On Menu bar issue,
I tried VLC(3.0.0), and yes, it has the same trouble.
But I'm using SMPlayer, and it does not have the issue, which is compiled by Qt 4.8.7.
Could that be a problem of Qt5?

Anyway, for the time being, Ubuntu 16.04 users might not use the options, `'Show Icon in notification area'` and `'Minimize to notification area when closed'`, becasue it has some issue.

I suggest you an option as a workaround, it could be good if you put a menu with the right click, on the left panel. Now there is only 'configure' menu on it, but you could attached the whole menu there. I'm just hoping. ^^

Anyway, thank you @CDrummond.
You may close this issue, because it seems to be the problem of Unity.

Regards,
J.

**Comment by CDrummond** [comment] 2016-03-17 08:07
The issue is a Qt5 issue (or Ubuntu's appmenu for Qt5). I have an idea for a workaround, which I'll try later. Probably won't work - but worth a try.

As to the position - Cantata does not save this in the config file, so leaves it up to the window manager to decide where to place.

**Comment by CDrummond** [comment] 2016-03-25 21:06
Closing - as this appears to be a Qt5/Ubuntu issue.

**Closed by CDrummond** 2016-03-25 21:06 UTC
