### ISSUE TITLE
Cover background not working when using MPD's "as_directory" playlist plugin, such as for CUE

### ISSUE THREAD

**Issue by vermeeren** [CDrummond/cantata#1652] opened 2020-11-17 00:46 UTC
**Describe the bug**
Now this is likely a bit broader of a bug, but it is most noticeable with the feature that displays the album cover in the background of the playlist:

![image](https://user-images.githubusercontent.com/5957454/99323807-3de99380-2873-11eb-90c1-9e165427ef7f.png)

I will try to be brief without omitting important details.

* Cantata's own CUE handling uses URI like `cue:///Some/Album/audio.cue?pos=4`.
* MPD's CUE handling uses URI like `Some/Album/audio.cue/track0004`

I believe at the time Cantata added CUE support MPD did not have this feature yet, or perhaps poorly. Nowadays it seems that MPD's CUE handling is pretty good. When using MPD's handling it is now possible to set rating per track instead of for the entire CUE file, and of course portability with MPD playlists and some other stuff.

Currently you also get duplicate entries that way. One from MPD and one from Cantata:

![image](https://user-images.githubusercontent.com/5957454/99324659-0b409a80-2875-11eb-82dd-29b0c1782613.png)

(I know there is an option to disable Cantata's CUE parsing in the settings.)

Interestingly MPD's `track0004` entry does not display the length of the track in the album search view, but it does display correctly in the playlist itself once added. Might a limitation of MPD API or Cantata bug.

**Expected behavior**
Background cover image works when using MPD's own CUE parser (as_directory).

**Version Info**
 - OS: Linux, Debian
 - Cantata Version: 2.4.0~git20190819.345c07d (I know is rather outdated, I checked sources of `master` and believe this still exists. I checked changelog.)
 - MPD Version: 0.22~git20200104.2164167 MPD-SACD https://sourceforge.net/p/sacddecoder/mpd/MPD.git/ci/master/tree/
 - CMake options (other than default):

**Potential fixes**
I think there are two specific points that could improve Cantata here, both are hopefully easy to fix.

* Disable Cantata's CUE parsing by default (or new installs), as recent MPD has this built-in natively. This avoids double entries and has other benefits mentioned above. https://www.musicpd.org/doc/html/user.html#configuring-playlist-plugins
* If the song path ends on `/track[0-9]+`, strip it away, so you get `Some/Album/audio.cue`, a real file, which should fix the `dirname` operation.
    * Where to do this is a point of interest. Just before album image lookup is likely rather late, I suspect this fake-track MPD causes issues with other functionality too. But not too early, as it is really the track path from MPD point of view.

If you need extra debug info or want me to try some patch/commit feel free to ask.

Thanks!

**Comment by CDrummond** [comment] 2020-11-17 12:08
I've update the code, and you check and see if this is now resolved? It appears to be for me.

**Comment by vermeeren** [comment] 2020-11-17 17:04
@CDrummond Thanks for the very fast fix.

I experimented a bit and initially had issues where huge parts of my library disappeared in the Library view. Refreshing the database also took really long (30-60sec) instead of just a few seconds, probably because my library is pretty big and the way the SQL query is written.

```
Artists: | 11113
-- | --
Albums: | 9337
Songs: | 115407
Duration: | 273:09:32:34
```

```cpp
    if (!mpdCueTrackDirs.isEmpty()) {
        DBUG << "Remove non-MPD cue tracks";
        for (const QString &d: mpdCueTrackDirs) {
            QSqlQuery(*db).exec("delete from songs where file like '" + d + "%%' and not file like '" + d + "%%/%%'");
        }
    }
```

Based upon this code I thought it was likely this was causing issues. I have a lot of tracks and albums with odd characters in them, and that definitely includes `[ ] ' "` and a lot more. This will then cause issues with this query here. After I commented out the query database refresh was very fast again and all the songs are back in the library view.

However I don't think there is a reason to have this query, refreshing the database builds the library view from scratch anyway I believe. Only old installations with Cantata's CUE parsing enabled will have duplicate entries without this query. If Cantata's CUE parsing is disabled a single database refresh will fix things up and remove all the duplicate entries.

Because sanitising a query might be rather difficult and there a lot of edge cases, I suggest something else for upgrades in the future. If MPD cue tracks are detected and Cantata's CUE parser is enabled display a warning dialogue that Cantata's own CUE parser is also enabled, which will result in duplicate tracks, with instructions on how to disable. Or perhaps a disable button in the popup itself to easily disable.

That logic could go into the current `if (!mpdCueTrackDirs.isEmpty())` conditional, replacing the query code.

**Comment by CDrummond** [comment] 2020-11-17 18:08
No. The problem is that MPD lists both the CUE contents (`path/a.cue/track0001`) and the file of the cue (`path/music.flac`) - and MPD gives me `path/music.flac` before `path/a.cue/track0001`. So, this source file will be in Cantata's DB before Cantata knows about the tracks. Hence these source tracks need to be removed. This is what that SQL is doing. I guess what I could do is run that SQL after all tracks are added.

Cantata's DB is refreshed from scratch each time, not updated.

I'm also not going to add any warnings - that would be new strings, and Cantata is feature (and hence string) frozen.

**Comment by CDrummond** [comment] 2020-11-17 18:46
Please update and try again - I've remove the SQL delete, and filtered out the tracks before they reach the DB.

**Comment by vermeeren** [comment] 2020-11-17 18:47
@CDrummond With most of the CUE files I have the actual audio file is TTA, which lacks any metadata. That could explain why I didn't see any duplicates, also not when using `mpc search` or similar. If I search for filenames in Cantata library I now indeed see the duplicates of the album as a single music file.

I guess what could also work is building up the query so that odd paths cannot escape the query and inject code or break things. I believe this is https://doc.qt.io/qt-5/qsqlquery.html#prepare and https://doc.qt.io/qt-5/qsqlquery.html#bindValue.

While I was typing this I noticed the new commit pop up, I will test it first, thanks!

**Comment by vermeeren** [comment] 2020-11-17 19:45
@CDrummond I tested and ea0610ba9c61eae938e748f7d765d9d12c4116fc and can confirm this solves it for 95% or so of the collection I have.

There are a few rare cases, such as multi-disc albums or layouts where subdirectories have bonus tracks or similar.

```
Album/CDImage1.tta
Album/CDImage1.cue
Album/CDImage2.tta
Album/CDImage2.cue

Album/Foo.flac
Album/Foo.cue
Album/Bonus/Bar.flac
Album/Bonus/Bar.cue
```

But really these are so edge case that I don't think it's worth the time solving them.

---

I do note that `mpc search` only lists the actual tracks and automatically excludes the main TTA file, except for when `file` search is used.

```console
$ mpc search filename 'Miscellaneous'
.../2008.05.25 [NTCD-0002] Miscellaneous Fragement [例大祭5]/Miscellaneous Fragement.tta
.../[N-tone]/2008.05.25 [NTCD-0002] Miscellaneous Fragement [例大祭5]/Miscellaneous Fragement.cue/track0001
...

$ mpc search any 'Miscellaneous'
.../2008.05.25 [NTCD-0002] Miscellaneous Fragement [例大祭5]/Miscellaneous Fragement.cue/track0001
...
```

I suspect `mpc search any` is really `any - filename`, and Cantata's `any` is truly `any`. If there is a very easy way to change the filter Cantata uses when refreshing DB that might solve it for 100% of cases. If there is no such thing the current solution is more than good enough. Thoughts?

**Comment by vermeeren** [comment] 2020-11-17 20:02
I checked `mpc` source code and it does something rather odd. https://github.com/MusicPlayerDaemon/mpc/blob/master/src/search.c#L33 Line 33 through 74 is relevant. Seems like `any` is not formally defined but a `+1`.

Then I did some searching and `grep` in Cantata and found following in the `ChangeLog` for Cantata 2.3.1.

> 18. When searching on 'any', do a second search on 'file' and combine results.
    Looks as if MPD does not search filenames/paths when using 'any.'

https://github.com/CDrummond/cantata/blob/master/mpd-interface/mpdconnection.cpp#L1955

@CDrummond That explains the behaviour I see in Cantata currently. For the Search tab this is definitely fine. Is it easily possible for the Library tab however to use `any` without combining it with `file`?

This depends on the architecture of Cantata I'd imagine. Here too if it isn't easily possible don't bother, just sharing some ideas.

**Comment by CDrummond** [comment] 2020-11-17 20:48
I'm closing this, as the issue itself is now resolved.

Cantata's library tab does not do an MPD search, but searches its cached DB. Only the search tab uses MPD's search.

Please note I no longer use Cantata nor MPD, so my time for these issues is very limited.

**Closed by CDrummond** 2020-11-17 20:48 UTC

**Comment by vermeeren** [comment] 2020-11-17 20:55
> Cantata's library tab does not do an MPD search, but searches its cached DB. Only the search tab uses MPD's search.

@CDrummond Yeah in that case there is no easy way to improve it further, understandable. Many thanks for fixing the issue, I appreciate it!
