### ISSUE TITLE
[Enhancement] Make Podcasts path configurable

### ISSUE THREAD

**Issue by msava** [CDrummond/cantata#1160] opened 2018-01-07 21:00 UTC
Would appreciate letting the user decide where to store the podcasts files, instead of dumping them in ~/Podcasts.

**Comment by CDrummond** [comment] 2018-01-08 08:42
This is **not** a bug - more a feature request.

**Comment by msava** [comment] 2018-01-08 15:12
I beg to differ!
It **is** a bug in the sense that it was an oversight on the part of the developers to include it alongside the other configurable path options.
But, it makes little difference to me how you chose to look at it as long as the issue itself gets the necessary attention.

**Comment by CDrummond** [comment] 2018-01-08 16:10
Oops! Sorry, for deleting your comment - clicked on wrong place! Any missing feature can be seen as a bug, depending upon the point of view. However, there is no crash involved, no data loss, the feature works as expected - hence not a bug.

**Comment by msava** [comment] 2018-01-08 18:08
Bugs come in all shapes and sizes, do they not? One could argue that an application that has one of its paths hardcoded instead of configurable is behaving badly -- hence bug.
I'm surprised you had the option to delete a comment that isn't yours -- was there no confirmation required? Perhaps you should open a ticket with GitHub about that.
Thanks!

**Comment by CDrummond** [comment] 2018-01-08 18:46
As project owner, I just click the 'x' and its gone :-)

Anyway, it's not behaving 'badly' - it's behaving as designed, and as it has since the feature was implemented years ago. I agree it'd be nice for the path to the configurable - hence  I have not closed the 'issue'

**Comment by CDrummond** [comment] 2018-01-08 18:56
Ah, now I am embarrassed :-) Cantata **did** have the option to specify the download path. During some code refactoring, this feature was not connected to the page's menu. I've now fixed this **bug** :-)

So, in 2.3 (which will be released soon-ish) you will be able to set the location.

**Closed by CDrummond** 2018-01-08 18:56 UTC
