### ISSUE TITLE
Request: [Ubuntu Touch] option to toggle diferent mpd outputs

### ISSUE THREAD

**Issue by Gorsh2** [CDrummond/cantata#719] opened 2015-08-05 18:22 UTC
First, congratulations on the app, it's great.

I have two outputs on my mpd.conf; a local and an http to play music through the net. Yesterday I woke up my neighbours trying to play some music outside :). So that, please implement some way of toggling outputs on and off (like gmpc, for example, has).

Thanks!

**Comment by CDrummond** [comment] 2015-08-05 20:46
Cantata already does this. There is an 'Outputs' sub-menu that should appear if you have more than 1 output, and in the 'Playback' section of the config dialog there should be a list of all outputs - with checkboxes to show the active ones.

I've just confirmed this is working by adding a HTTP output to my mpd.conf

**Comment by Gorsh2** [comment] 2015-08-05 21:15
It's not showing on mine, then. It's on Ubuntu Touch, on a Nexus 4; Cantata v.0.2.0.

Maybe I posted in the wrong section? I'm now unsure if this is the right place to post it.

**Comment by Gorsh2** [comment] 2015-08-05 21:21
Yeah; it seems "nikwen" is that version's developer; I should go bother him instead. Sorry and thanks!

**Comment by CDrummond** [comment] 2015-08-06 07:53
Ah, that version of Cantata is **very** much a preview - and is no longer actively developed. It has **many** missing features, and issues. I was not responsible for it, and as you noticed 'nkiwen' did the *port* to Ubuntu touch. Perhaps you should get in contact with him?

Sorry - but I'm 99.99% sure that that version no longer even compiles, and is not on my list of issues to fix. Perhaps one day it will be resurrected, but for now I'm more interested in creating a HTML5/Javascript UI that will run under any browser - this seems to make more sense to me. I have started on this, but again it is not yet usable (and I have not worked on it for some months...)

So, I'm going to close this - as its not relevant to this version of Cantata

**Comment by nikwen** [comment] 2015-08-06 21:43
Please reopen the issue. I got an email from @Gorsh2 and I'll look into this. I'll send you a more detailed message at the weekend. ;)

**Comment by CDrummond** [comment] 2015-08-07 07:26
OK, thought you had given up on this - seeing as you had been quiet for so long :-)

Note, however, that (as stated above) I'm 99.9999% sure that git/master will no longer build for Ubuntu Touch

**Comment by nikwen** [comment] 2015-08-09 21:29
Hi Craig, hi Jorge,

You're right. I have been quite for a very long time.

When I left Cantata, I didn't really think I was leaving. I began working on my own application, Forum Browser, and thought I'd soon work on both projects in parallel. Somehow it didn't work out that way and at some point I stopped using MPD because I stopped listening to music at all. However, I always had a bad conscience because I left Cantata's Ubuntu version in a very bad state. I had huge plans for it and started working on a converged interface when the Ubuntu UI Toolkit was by far not ready for this.

So the thought of cleaning up the source code and making it usable again has been in the back of my mind for the last few months and Jorge's message finally pushed me towards putting it on my todo list for the nearest future again.

Due to [bad news](https://plus.google.com/101390620047921378812/posts/ZxbTPMzjsaU) for the Forum Browser app, I didn't feel motivated to work on it this weekend. However, I'll soon do so, given, of course, that the required work to make it compile again isn't too much. Nevertheless, that one feature will probably be the goodbye from me.

Therefore, Jorge, I'd like to come back to the offer/request from the mail you sent me. You asked whether you could help me implementing that feature. Given that you still use the application and that I don't, what do you think about me bringing the app's source code back into a working state and then helping you to write the output selection settings?
After all, porting that feature to the mobile version shouldn't be that hard and if all goes well what do you think about me handing over the development of the Ubuntu Phone version to you? With me it would probably not get any further improvements anytime soon.

Let me hear what you think.

Cheers,
Niklas

**Comment by nikwen** [comment] 2015-08-24 11:41
Hi all, I'm still waiting for your replies. What do you think about what I wrote above? (This especially goes out to @Gorsh2.)

**Comment by Gorsh2** [comment] 2015-08-29 17:34
Hi, sorry to keep you waiting, I miss the first email and then took some time to answer this one.

I'm sorry but I don't think I can take charge of the project: I have the desire, but I'm far from a real programmer (besides the ocasional bash script and such) so I think it would be too much for me; when I said I wanted to help I meant like to give logs and test patches... With more time in my hands I could try to rise up to the challenge (and surely learn a lot on the process) but I don't think I can at the moment. Sorry...


      De: Niklas Wenzel <notifications@github.com>
 Para: CDrummond/cantata <cantata@noreply.github.com> 
CC: Gorsh <copateymandameunmail@yahoo.com.ar> 
 Enviado: Lunes, 24 de agosto, 2015 8:41:15
 Asunto: Re: [cantata] Request: [Ubuntu Touch] option to toggle diferent mpd outputs (#719)
   
Hi all, I'm still waiting for your replies. What do you think about what I wrote above? (This especially goes out to @Gorsh2.)—

**Comment by CDrummond** [comment] 2015-08-30 09:35
Just got back from holiday. However, as I stated I'm 99.9999999% sure the Ubuntu touch builds no longer compile. Seeing as no-one seems to want to take care of this, I'm inclined to close this report.

As for touch builds - as stated, I have started on a Javascript/HTML5 version, and I think this makes more sense. It will then work whatever OS is used - however, would not be 10% native.

So, closing this issue.

**Closed by CDrummond** 2015-08-30 09:35 UTC

**Comment by nikwen** [comment] 2015-09-16 16:09
Being back from holiday myself now, I can comment on the issue again.
It's no problem if you don't want to take over the project. I'm still going to clean up the Touch codebase in the near future as long as it isn't too difficult (and yes, I am aware of the fact that it does no longer compile) and if implementing this feature doesn't turn out to be too complicated, I'll also try to do this. No promises regarding that though. ;)

@Craig Looking forward to the web version. :)
