### ISSUE TITLE
Cue files not properly handled after restart

### ISSUE THREAD

**Issue by remipp** [CDrummond/cantata#1720] opened 2021-06-02 23:19 UTC
**NOTE** Cantata is now in a bug-fix only state. Only bugs that are actual bugs, and not missing functionality will be fixed. Pull requests, however, will still be accepted.
---
---

**Describe the bug**
If an album using a cue file is added to the play queue the cue file is handled correctly at first, however if one then restarts cantata, album name and artist are displayed as "Unknown" and tracks are labelled "track0001", "track0002", ...

**To Reproduce**
1. Add album with cue file to play queue
2. Close cantata
3. Launch cantata

**Expected behavior**
The play queue should be the same as it was prior to restarting

**Version Info**
 - OS: Linux
 - Cantata Version: master
 - MPD Version: 0.22.8
 - CMake options (other than default):

**Additional context**
I'm using the default configuration with mpd managed by cantata

**Comment by CDrummond** [comment] 2021-06-03 06:11
This _looks_ like MPD is not passing the song details to Cantata - these `track000X` names are coming from MPD, and are not created by Cantata. If track title, artist, album, etc. are not passed by MPD Cantata will attempt to "fake" these by using the filename and path. Cantata does not do any CUE parsing for the queue and just uses the info supplied from MPD. I'm guessing the issue is the Cantata started MPD, as you are using a very new MPD, is not 100% configured correctly. I suggest you use a system-wide MPD and see if that resolves the issues. Also, check with other clients.

Cantata's 'Basic' mode is named this way for a reason.

**Comment by remipp** [comment] 2021-06-03 09:19
Thanks, this looks like an mpd problem unless there is some configuration option I'm missing. I was able to reproduce this using a system-wide mpd with mpc, xfmpc, and ario. Can you verify that this doesn't happen with your version of mpd? I'll do some more digging and see if I should open an issue with mpd for this.

**Comment by CDrummond** [comment] 2021-06-03 15:58
Sorry, my MPD version is older than this feature, so I cannot confirm. However, if other clients show this issue then it is not a Cantata issue.

Therefore, I'm going to close this. Sorry, but I no longer actively use MPD nor Cantata - switched to LMS about 4 years ago.

**Closed by CDrummond** 2021-06-03 15:58 UTC
