### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by nousernouser** [CDrummond/cantata#1578] opened 2020-03-13 18:26 UTC
Hi CDrummond

Trying to build 2.4.1 code (latest commit 5a8fcd0) on a Debian/Devuan machine (kernel 4.6.4-1~bpo8+1 (2016-08-11) x86_64 I have this error:
~~~
[  5%] Building CXX object replaygain/CMakeFiles/cantata-replaygain.dir/main.cpp.o
[  5%] Building CXX object support/CMakeFiles/support-core.dir/thread.cpp.o
/media/SOFTWARE/BUILDS/amd64/cantata/cantata-2.4.1-build-5a8fcd0/cantata-2.4.1-5a8fcd0/support/fancytabwidget.cpp: In member function ‘virtual QSize FancyTab::sizeHint() const’:
/media/SOFTWARE/BUILDS/amd64/cantata/cantata-2.4.1-build-5a8fcd0/cantata-2.4.1-5a8fcd0/support/fancytabwidget.cpp:272:28: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
         int textWidth = fm.horizontalAdvance(text)*1.1;
~~~

Thank you in advance for your support.
Regards

**Comment by CDrummond** [comment] 2020-03-13 19:12
Please look for existing issues (even if closed) **before** reporting new ones.

Duplicate of https://github.com/CDrummond/cantata/issues/1574

**Closed by CDrummond** 2020-03-13 19:12 UTC
Labels: duplicate
