### ISSUE TITLE
Cantata adds numbers to song titles

### ISSUE THREAD

**Issue by officernice** [CDrummond/cantata#1665] opened 2021-01-14 17:45 UTC
Hello there. First off, thank you for this amazing music player. It's my number one choice! :) 

I've run into this problem with tracks that has the percentage symbol % in the title where it always adds 25 to it.
So songs like ...
100% Gangstaz >> 100%25 Gangstaz
#%!@ mig nu >> #%25!@ mig nu

I've tried putting such songs into all kinds of players but it only happens in Cantata. :(

OS: Arch Linux
Cantata V: 2.4.2-1

**Comment by CDrummond** [comment] 2021-01-14 18:51
Duplicate of #1664

**Closed by CDrummond** 2021-01-14 18:51 UTC
Labels: duplicate
