### ISSUE TITLE
Albums with multiple genres don't show up

### ISSUE THREAD

**Issue by gbindea** [CDrummond/cantata#735] opened 2015-09-13 18:27 UTC
Cantata version 1.5.2

Hi, thanks for the great work on cantata. I just saw a bug/or I did something wrong.
When I have Albums with multiple genres (like Rock;Pop) then when I select e.g. Pop in the pull down menu, the Album doesn't show up. Did I do something wrong? Is ; the proper separator? It seems separated properly because I don't see Rock;Pop in pull down menu, but I see Pop and below Rock.
Thanks for your help
Best

**Comment by CDrummond** [comment] 2015-09-15 19:18
I was about to state that this all works fine, but then I tested the Albums and Playlists views... Looks like this multiple genre handling only works for the Artists view. So, yeah, this is a bug - sorry.

However, the issue is that 1.x is no longer being developed - and I'm working on 2.x now. This no longer has the genre combo. Instead, you can now choose to have artists grouped by genre - as per most other media players. The Artists and Albums views have been combined into 1 Library view - with different grouping options (Genre/Artist/Album, Artist/Album, or just Album)

Because of this, I'm going to close this.

**Closed by CDrummond** 2015-09-15 19:18 UTC
