### ISSUE TITLE
Implement changing volume level via scrolling mouse under Cantata tray icon.

### ISSUE THREAD

**Issue by IlyaIndigo** [CDrummond/cantata#959] opened 2017-02-09 02:48 UTC
Implement changing volume level via scrolling mouse under Cantata tray icon.

**Comment by CDrummond** [comment] 2017-02-09 08:13
Please search exsting (and closed) issues before reporting new ones. Duplicate of #940

**Closed by CDrummond** 2017-02-09 08:13 UTC
