### ISSUE TITLE
Segfault on playing streams

### ISSUE THREAD

**Issue by frispete** [CDrummond/cantata#770] opened 2015-11-28 21:35 UTC
Dear Craig,

I'm still lagging a few commits (280f081), wanted to let you know about a reproducible crash, when attempting to play a http stream from a server. Clicking on "Play stream" config immediately results in:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbb2b7700 (LWP 32290)]
0x00007fffb966f22e in _GLOBAL__sub_I_kauthactionwatcher.cpp () from /usr/lib64/libkdecore.so.5
(gdb) bt
#0  0x00007fffb966f22e in _GLOBAL__sub_I_kauthactionwatcher.cpp () at /usr/lib64/libkdecore.so.5
#1  0x00007ffff7dea92a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffd878, env=env@entry=0x7fffffffd888) at dl-init.c:78
#2  0x00007ffff7deaa13 in _dl_init (env=0x7fffffffd888, argv=0x7fffffffd878, argc=1, l=<optimized out>) at dl-init.c:36
#3  0x00007ffff7deaa13 in _dl_init (main_map=main_map@entry=0x7fffb4014470, argc=1, argv=0x7fffffffd878, env=0x7fffffffd888) at dl-init.c:126
#4  0x00007ffff7deeb48 in dl_open_worker (a=a@entry=0x7fffbb2b5818) at dl-open.c:566
#5  0x00007ffff7dea7e4 in _dl_catch_error (objname=objname@entry=0x7fffbb2b5808, errstring=errstring@entry=0x7fffbb2b5810, mallocedp=mallocedp@entry=0x7fffbb2b5807, operate=operate@entry=0x7ffff7dee870 <dl_open_worker>, args=args@entry=0x7fffbb2b5818) at dl-error.c:187
#6  0x00007ffff7dee33b in _dl_open (file=0x7fffb4012998 "/usr/lib64/libproxy-0.4.11/modules/config_kde4.so", mode=-2147483647, caller_dlopen=<optimized out>, nsid=-2, argc=1, argv=0x7fffffffd878, env=0x7fffffffd888) at dl-open.c:650
#7  0x00007ffff224b02b in dlopen_doit (a=a@entry=0x7fffbb2b5a30) at dlopen.c:66
#8  0x00007ffff7dea7e4 in _dl_catch_error (objname=0x7fffb400de70, errstring=0x7fffb400de78, mallocedp=0x7fffb400de68, operate=0x7ffff224afd0 <dlopen_doit>, args=0x7fffbb2b5a30) at dl-error.c:187
#9  0x00007ffff224b5dd in _dlerror_run (operate=operate@entry=0x7ffff224afd0 <dlopen_doit>, args=args@entry=0x7fffbb2b5a30) at dlerror.c:163
#10 0x00007ffff224b0c1 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#11 0x00007fffeb24ef25 in libmodman::module_manager::load_file(std::string, bool) (this=this@entry=0x7fffb40141b8, filename="/usr/lib64/libproxy-0.4.11/modules/config_kde4.so", symbreq=symbreq@entry=true)
    at /usr/src/debug/libmodman-2.0.1/libmodman/module_manager.cpp:250
#12 0x00007fffeb24f2b3 in libmodman::module_manager::load_dir(std::string, bool) (this=this@entry=0x7fffb40141b8, dirname="/usr/lib64/libproxy-0.4.11/modules", symbreq=symbreq@entry=true)
    at /usr/src/debug/libmodman-2.0.1/libmodman/module_manager.cpp:327
#13 0x00007fffefe26e06 in libproxy::proxy_factory::proxy_factory() (this=0x7fffb4014190)
    at /usr/src/debug/libproxy-0.4.11/libproxy/proxy.cpp:165
#14 0x00007fffefe279bb in px_proxy_factory_new() (this=0x7fffb4014190)
    at /usr/src/debug/libproxy-0.4.11/libproxy/proxy.cpp:449
#15 0x00007fffefe279bb in px_proxy_factory_new() () at /usr/src/debug/libproxy-0.4.11/libproxy/proxy.cpp:454
#16 0x00007fffb9ca16f9 in g_libproxy_resolver_init (resolver=0x3065da0 [GLibProxyResolver]) at glibproxyresolver.c:77
#17 0x00007ffff1d1c0ab in g_type_create_instance (type=<optimized out>) at gtype.c:1865
#18 0x00007ffff1d00ebd in g_object_new_internal (class=class@entry=0x7fffb4014100, params=params@entry=0x0, n_params=n_params@entry=0) at gobject.c:1774
#19 0x00007ffff1d029cd in g_object_newv (object_type=object_type@entry=140736213348128, n_parameters=n_parameters@entry=0, parameters=parameters@entry=0x0) at gobject.c:1922
#20 0x00007ffff1d0317c in g_object_new (object_type=object_type@entry=140736213348128, first_property_name=first_property_name@entry=0x0) at gobject.c:1614
#21 0x00007fffc4c9d311 in try_implementation (extension=<optimized out>, verify_func=verify_func@entry=0x7fffc4cac080 <g_proxy_resolver_is_supported>) at giomodule.c:758
#22 0x00007fffc4c9d490 in _g_io_module_get_default (extension_point=extension_point@entry=0x7fffc4d3b614 "gio-proxy-resolver", envvar=envvar@entry=0x7fffc4d44c56 "GIO_USE_PROXY_RESOLVER", verify_func=verify_func@entry=0x7fffc4cac080 <g_proxy_resolver_is_supported>) at giomodule.c:857
#23 0x00007fffc4cac10a in g_proxy_resolver_get_default () at gproxyresolver.c:63
#24 0x00007fffc4cab49d in g_proxy_address_enumerator_set_property (object=<optimized out>, property_id=<optimized out>, value=<optimized out>, pspec=0x7fffb400c120 [GParamObject]) at gproxyaddressenumerator.c:655
#25 0x00007ffff1d01269 in g_object_new_internal (nqueue=0x2c9dca0, value=<optimized out>, pspec=0x7fffb400c120 [GParamObject], object=0x7fffb400e0b0 [GProxyAddressEnumerator]) at gobject.c:1415
#26 0x00007ffff1d01269 in g_object_new_internal (class=class@entry=0x7fffb400dd50, params=params@entry=0x7fffbb2b6400, n_params=2) at gobject.c:1808
#27 0x00007ffff1d02d84 in g_object_new_valist (object_type=object_type@entry=140736213343088, first_property_name=first_property_name@entry=0x7fffc5030069 "connectable", var_args=var_args@entry=0x7fffbb2b6558) at gobject.c:2034
#28 0x00007ffff1d03164 in g_object_new (object_type=140736213343088, first_property_name=first_property_name@entry=0x7fffc5030069 "connectable") at gobject.c:1617
#29 0x00007fffc4ff383e in soup_address_connectable_proxy_enumerate (connectable=0x2f72ca0) at soup-address.c:1272
#30 0x00007fffc4cb8206 in g_socket_client_connect_async (client=0x2f72c40 [GSocketClient], connectable=0x2f72ca0, cancellable=0x7fffb4001360 [GCancellable], callback=0x7fffc5027380 <async_connected>, user_data=0x2bf05b0)
    at gsocketclient.c:1673
#31 0x00007fffc5027d4d in soup_socket_connect_async_internal (sock=<optimized out>, cancellable=cancellable@entry=0x7fffb4001360 [GCancellable], callback=callback@entry=0x7fffc5001df0 <socket_connect_complete>, user_data=0x2bf04e0)
    at soup-socket.c:938
#32 0x00007fffc5001d1c in soup_connection_connect_async (conn=0x7fffb40036c0 [SoupConnection], cancellable=0x7fffb4001360 [GCancellable], callback=0x7fffc50249b0 <connect_async_complete>, user_data=0x2c1ae40) at soup-connection.c:421
#33 0x00007fffc50245e7 in soup_session_process_queue_item (should_cleanup=<optimized out>, item=0x2c1ae40)
    at soup-session.c:1933
#34 0x00007fffc50245e7 in soup_session_process_queue_item (session=session@entry=0x2c1c150 [SoupSessionAsync], item=item@entry=0x2c1ae40, should_cleanup=should_cleanup@entry=0x7fffbb2b680c, loop=loop@entry=1) at soup-session.c:1960
#35 0x00007fffc50248a9 in async_run_queue (session=0x2c1c150 [SoupSessionAsync]) at soup-session.c:2059
#36 0x00007fffc502497b in idle_run_queue (user_data=0x2c1c040) at soup-session.c:2093
#37 0x00007ffff1f878e5 in g_main_context_dispatch (context=0x2c16970) at gmain.c:3111
#38 0x00007ffff1f878e5 in g_main_context_dispatch (context=context@entry=0x2c16970) at gmain.c:3710
#39 0x00007ffff1f87c48 in g_main_context_iterate (context=0x2c16970, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3781
#40 0x00007ffff1f87f0a in g_main_loop_run (loop=0x2c16650) at gmain.c:3975
#41 0x00007fffc5285f01 in gst_soup_http_src_do_request (src=0x2c14110 [GstSoupHTTPSrc], method=0x7fffc528919e "GET", outbuf=0x7fffbb2b6ae0) at gstsouphttpsrc.c:1740
#42 0x00007fffc528605e in gst_soup_http_src_create (psrc=0x2c14110 [GstSoupHTTPSrc], outbuf=0x7fffbb2b6ae0)
    at gstsouphttpsrc.c:1792
#43 0x00007fffd4501aa9 in gst_base_src_get_range (src=src@entry=0x2c14110 [GstSoupHTTPSrc], offset=offset@entry=0, length=length@entry=4096, buf=buf@entry=0x7fffbb2b6be8) at gstbasesrc.c:2455
#44 0x00007fffd4503603 in gst_base_src_loop (pad=0x2be9250 [GstPad]) at gstbasesrc.c:2731
#45 0x00007fffd4254279 in gst_task_func (task=0x2e8c050 [GstTask]) at gsttask.c:331
#46 0x00007ffff1fad50c in g_thread_pool_thread_proxy (data=<optimized out>) at gthreadpool.c:307
#47 0x00007ffff1facb85 in g_thread_proxy (data=0x2c08ed0) at gthread.c:764
#48 0x00007ffff45c00a4 in start_thread (arg=0x7fffbb2b7700) at pthread_create.c:309
#49 0x00007ffff3ad608d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by CDrummond** [comment] 2015-11-29 08:39
What stream is this? A radio stream, or an MPD HTTP output stream? Also, there is no mention of Cantata code in that backtrace.

**Comment by frispete** [comment] 2015-11-29 13:06
It's a mp3 http stream from the MPD server, defined as:
```
audio_output {
        type            "httpd"
        name            "mpd stream"
        encoding        "mp3"
        port            "8800"
        bind_to_address "ip.address"
        bitrate         "192"
        format          "44100:16:2"
        max_clients     "5"
}
```
I noticed the absence of cantata, too, but this happens reproducible, if I click on "Play stream". Since I just started using mpd with streaming, I don't have any other experience. All I see is mpd server socket waiting for connections.

Will reboot and recheck..

**Comment by frispete** [comment] 2015-11-29 14:19
Crash 100% reproducible on my system. Could you point me to the related part of cantata code? 
BTW, have you tried to play a mpd stream yourself lately?

**Comment by CDrummond** [comment] 2015-11-29 22:37
So, the crash is when playing back the MPD stream. Which build is this Qt4? Qt5? KDE4?

Can you try compiling with libvlc?

**Comment by frispete** [comment] 2015-11-29 23:18
This is a Qt5 build, as suggested from you. A libvlc build is going to give me some headaches, since I build in public... Will check a local build tomorrow... 

Thanks, Craig.

**Comment by CDrummond** [comment] 2015-11-30 08:15
Not sure I have ever suggested Qt5 builds - I always use Qt4 builds. Anyway, the issue is in the library that is playing back the stream - not sure there is much Cantata can do, hence trying libvlc

**Comment by CDrummond** [comment] 2015-12-05 10:38
Any update on this?

**Comment by CDrummond** [comment] 2015-12-06 10:55
Just tried Qt5 builds. With QtMultimedia - no segfault, but playback not working. With LibVLC,playback works fine.

**Comment by frispete** [comment] 2015-12-06 11:51
Sorry for the delay, Craig, and thanks for the feedback.

FYI, I noticed, that global shortcuts do not work either in the Qt5 build, will switch to Qt4 in the next few days...

**Comment by CDrummond** [comment] 2015-12-06 13:47
I'm closing this - as Qt5 (with VLC on Linux, QtMultiMedia on OSX) works just fine. I have also changed the builds to use VLC by default on Linux. The crash looks like its happening in gstreamer - but whatever, the crash is not in Cantata code, so nothing I can do.

As to media keys - working fine for me with Qt5 in both Plasma5 and Unity.

**Closed by CDrummond** 2015-12-06 13:47 UTC
