### ISSUE TITLE
Group songs by grouping, album artist, and then artist.

### ISSUE THREAD

**Issue by crocket** [CDrummond/cantata#1561] opened 2019-12-21 02:03 UTC
**Describe the solution you'd like**

If you group songs by genre, in each genre, you see songs grouped by grouping, album artist, or artist.

If you group songs by artist, you see songs grouped by grouping, album artist, or artist.

According to [Foobar2000:ID3 Tag Mapping - Hydrogenaudio Knowledgebase](http://wiki.hydrogenaud.io/index.php?title=Foobar2000:ID3_Tag_Mappingi), TIT1 tag in id3 is grouping tag in vorbis comment.

According to [id3v2.4.0 frames](http://id3.org/id3v2.4.0-frames),

> TIT1
The 'Content group description' frame is used if the sound belongs to a larger category of sounds/music. For example, classical music is often sorted in different musical sections (e.g. "Piano Concerto", "Weather - Hurricane").

Mpd currently exposes grouping tag.

**Additional context**

Currently, songs are grouped by album artist and artist

* inside each genre
* when you group songs by artist.

**Comment by CDrummond** [comment] 2019-12-21 08:39
Duplicate of https://github.com/CDrummond/cantata/issues/1493

**Closed by CDrummond** 2019-12-21 08:39 UTC

**Comment by crocket** [comment] 2019-12-21 10:26
I made it far simpler to implement by proposing a minimal change. Do you want to move on from cantata?

**Comment by CDrummond** [comment] 2019-12-21 13:14
If its so simple, I look forward to your pull request to implement this. Sorry, but I'll spend my time on features I want.

Also, Cantata is in a bug-fix only state - as stated in the linked issue.

**Comment by crocket** [comment] 2019-12-21 14:28
Okay. I just perused the codebase to see what I could do. It's a lot more complex than I though it would be, and you don't want to trust my C++ skill.

I guess I will stick with minimal solutions such as using file browser or album artist tag.
