### ISSUE TITLE
Latest windows binary

### ISSUE THREAD

**Issue by alekstj** [CDrummond/cantata#1580] opened 2020-03-24 13:44 UTC
Please, create latest version binary for windows. The are is best mpd client for linux and windows.

**Comment by CDrummond** [comment] 2020-03-24 14:38
Sorry, I no longer have a windows machine. Cantata is opensource, so ypu should be able to create your own. Asstated in **many** bug reports, I no longer actively use Cantata nor MPD - switch to logitech media server over 3 years ago.

Duplicate of #1534

**Closed by CDrummond** 2020-03-24 14:38 UTC
Labels: duplicate
